namespace A2AServer;

public class APIKeySettings
{
    /// <summary>Optional secret used to sign the API keys generated by the AuthAgent (HMAC-SHA256).
    /// Keep it in user secrets or an environment variable, never in appsettings.json.
    /// When empty, a random secret is generated at startup: the keys are then valid until the server stops.</summary>
    public string? SecretKey { get; set; }
}
